env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules: {
  no-console: ["error", { allow: ["info", "error"] }],
  no-unused-vars: ["error", { "argsIgnorePattern": "^_" }]
}
